version: 2
jobs:
  build:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            mkdir -p ~/.virtualenvs
            apk add build-base libffi-dev
            pip install virtualenv
            python -m virtualenv ~/.virtualenvs/tap-slack
            source ~/.virtualenvs/tap-slack/bin/activate
            pip install -U 'pip<19.2' setuptools
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source ~/.virtualenvs/tap-slack/bin/activate
            pylint tap_slack -d C,R,W,no-member
